### ISSUE TITLE
Find Potential APIs for AIS and ship data

### ISSUE THREAD

**Issue by jon-bwc** [bytewisecoding/mmst#9]
Find a couple of data sources for near real time AIS ship data, and ship/vessel databases

**Comment by schnozeprime** [comment]
Freightify api, searates, GComet, Kuehne+Nagel, Flexport API

**Comment by mrdog233o5** [comment]
# websites:

- [Vessel Finder](https://www.vesselfinder.com/)
> This website have ***IMAGES*** of the ships
> This website have ships ***GLOBALLY***
> This website have data of ships that are ***FAR FROM COASTAL AREAS*** (I think its tracked by satillites)

- [My Ship Tracking](https://www.myshiptracking.com/)
> This website have ***IMAGES*** of the ships
> This website have ships ***GLOBALLY***

- [Sea Routes](https://searoutes.com/vessel-api/)
> This website calculates the ***CARBON EMMISIONS***
> I dont see any examples
